#####DON'T EDIT#####
config-version: 'v1'
####################

#Database settings
db-host: 'localhost'
db-port: '3306'
db-name: 'linkbe'
db-user: 'root'
db-pass: ''

#General settings
code-length: '8'